[WIP] Expose per_connection_buffer_limit_bytes
emissary-ingress/emissary pull request #3664
Opened 2021-08-04 23:46 UTC by AliceProxy

Signed-off-by: AliceProxy <aliceproxy@protonmail.com>

## Description
Makes the Envoy setting `per_connection_buffer_limit_bytes` configurable via the `Module`. Using the default Envoy value of 1MiB unless configured in the Module. 

## Related Issues
List related issues.

## Testing
A few sentences describing what testing you've done, e.g., manual tests, automated tests, deployed in production, etc.

## Checklist

 - [ ] I made sure to update `CHANGELOG.md`.
   
   Remember, the CHANGELOG needs to mention:
    + Any new features
    + Any changes to our included version of Envoy
    + Any non-backward-compatible changes
    + Any deprecations
 
 - [ ] This is unlikely to impact how Ambassador performs at scale.
 
   Remember, things that might have an impact at scale include:
    + Any significant changes in memory use that might require adjusting the memory limits
    + Any significant changes in CPU use that might require adjusting the CPU limits
    + Anything that might change how many replicas users should use
    + Changes that impact data-plane latency/scalability
 
 - [ ] My change is adequately tested.
 
   Remember when considering testing:
    + LEGACY MODE TESTS DO NOT RUN FOR EVERY PR. If your change is affected by legacy mode, you need
      to run legacy-mode tests manually (set `AMBASSADOR_LEGACY_MODE=true` and run the tests).
      (This will be fixed soon.)
    + Your change needs to be specifically covered by tests.
       + Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
    + You also need to make sure that the _entire area being changed_ has adequate test coverage.
       + If existing tests don't actually cover the entire area being changed, add tests.
       + This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
    + We should lean on the bulk of code being covered by unit tests, but...
    + ... an end-to-end test should cover the integration points
 
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

2021-09-07 15:32 UTC, kflynn requested changes
Just a few small comments -- thanks!! 🙂

2021-09-07 15:32 UTC, kflynn commented on python/ambassador/envoy/v3/v3listener.py
> +            listener.__setitem__("per_connection_buffer_limit_bytes", self.config.ir.ambassador_module.buffer_limit_bytes)
Here, too.

2021-09-07 15:32 UTC, kflynn commented on python/tests/kat/t_bufferlimitbytes.py
> +        yield self, self.format("""
Huh. I'm not sure I follow how this test really works?

2021-09-17 18:31 UTC, AliceProxy commented
Closed for duplicate branch. Merged in #3788

2021-09-17 18:31 UTC, closed without merging