Repatriate to master
emissary-ingress/emissary pull request #3827
Opened 2021-09-23 22:29 UTC by aidanhahn

## Description
This PR contains a CI job to automatically repatriate changes pushed to release/v2.0 back to master.

2021-09-23 22:31 UTC, anodelman requested changes

2021-09-23 22:31 UTC, anodelman commented on .github/workflows/repatriate-lts.yml
> +      GIT_API_KEY: ${{ secrets.GH_API_KEY }}
Should be GH_GITHUB_API_KEY?

2021-09-23 22:49 UTC, anodelman commented on .github/workflows/repatriate-lts.yml
> +      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
You don't need this, use GH_GITHUB_API_KEY.  token=api key.

2021-09-23 22:49 UTC, anodelman commented on .github/workflows/repatriate.yml
>        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
This should be GH_GITHUB_API_KEY.

2021-09-24 17:33 UTC, kflynn approved these changes
Hit it!

2021-09-24 17:34 UTC, anodelman approved these changes
Look at that token usage!

2021-09-24 18:25 UTC, merged