Stop sending upstreams encoded data when using gzip
emissary-ingress/emissary pull request #3967
Opened 2021-12-04 00:53 UTC by AliceProxy

Signed-off-by: AliceProxy <aliceproxy@protonmail.com>

## Description
Fixes a bug introduced in `1.14.0` where upstream services would receive gzip encoded data when using gzip compression in the `Module`.

Thanks to @kflynn for finding the fix

## Related Issues
https://github.com/emissary-ingress/emissary/issues/3818

## Notes:
A future version of edgissary may expose the ability to enable sending encoded data to upstream, but the default should be to not do that.

2021-12-04 00:56 UTC, kflynn approved these changes
Ahh, need to update `docs/releaseNotes.yml` and then run `make generate-fast` to get the `CHANGELOG` too. 🙂  Code looks good though!

2021-12-04 00:57 UTC, kflynn requested changes
D'oh. Meant to request changes instead of approve. 🙄

2021-12-04 05:00 UTC, kflynn requested changes
Sorry, one more minor thing! 😐

2021-12-04 05:17 UTC, kflynn approved these changes
Off we go! Thanks @AliceProxy! 🙂 

(Yes, I force-pushed it, that's 'cause I need to sync release notes with the docs. 🙂)

2021-12-04 05:26 UTC, kflynn approved these changes
Yes yes, still approved after a typo fix. 🙂

2021-12-04 06:11 UTC, merged

2022-04-29 12:21 UTC, sharkymcdongles commented
Any chance you can backport this fix to 1.14.x?

2022-09-06 13:23 UTC, mrnonz commented
Hope this view release to v1.14.5 too https://github.com/emissary-ingress/emissary/blob/master/CHANGELOG.md#1145-tbd

2022-09-20 16:12 UTC, AliceProxy commented
> Hope this will release to v1.14.5 too https://github.com/emissary-ingress/emissary/blob/master/CHANGELOG.md#1145-tbd

@mrnonz @sharkymcdongles We currently have no plans of officially releasing a `1.14.5`, but we did end up doing a dev build of `1.14` containing the gzip bug fix because a specific customer was unable to upgrade Edge-Stack from a much older version to `1.14.4` in order to get on the new the new 2.x line due to this bug. The `TBD 1.14.5` exists as a placeholder because `1.14` is still in extended maintenance mode.

This means that should Envoy release security patches for discovered CVEs before `1.14` hits its full End of Life, we would port said security patches back into `1.14` necessitating the `1.14.5` release. Given that this has already been finished and tested for a dev-build, we would include it in said `1.14.5` release if that scenario were to happen, but if not then there will not be a `1.14.5` release.

I can provide the image for the dev-build if you need it because you are in a similar situation, but please understand that dev-builds do not go through the full suite of testing that regular release images do. Additionally, I would strongly recommend only using it as a stepping-stone to help upgrade to 2.x since as I mentioned, unless there are high severity security patches that we need to backport, `1.14` will not receive any additional support, updates, or bugfixes before its EOL. 

Edge-stack dev-build: `datawiredev/aes:1.14.5-hf.1-1956`

For emissary I do not have an image on-hand to provide, but you can build your own off of the [release/v1.14](https://github.com/emissary-ingress/emissary/tree/release/v1.14) branch. Let me know if you need any assistance doing so if you are using Emissary instead of Edge-Stack.