chart: Set module.diagnostics.enabled=false by default
emissary-ingress/emissary pull request #4295
Opened 2022-06-20 19:24 UTC by LukeShu

## Description
A few sentences describing the overall goals of the pull request's commits.

## Related Issues
List related issues.

## Testing
A few sentences describing what testing you've done, e.g., manual tests, automated tests, deployed in production, etc.

## Checklist

 - [ ] I made sure to update `CHANGELOG.md`.

   Remember, the CHANGELOG needs to mention:
    + Any new features
    + Any changes to our included version of Envoy
    + Any non-backward-compatible changes
    + Any deprecations

 - [ ] This is unlikely to impact how Ambassador performs at scale.

   Remember, things that might have an impact at scale include:
    + Any significant changes in memory use that might require adjusting the memory limits
    + Any significant changes in CPU use that might require adjusting the CPU limits
    + Anything that might change how many replicas users should use
    + Changes that impact data-plane latency/scalability

 - [ ] My change is adequately tested.

   Remember when considering testing:
    + Your change needs to be specifically covered by tests.
       + Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
    + You also need to make sure that the _entire area being changed_ has adequate test coverage.
       + If existing tests don't actually cover the entire area being changed, add tests.
       + This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
    + We should lean on the bulk of code being covered by unit tests, but...
    + ... an end-to-end test should cover the integration points

 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

 - [ ] The changes in this PR have been reviewed for security concerns and adherence to security best practices.

2022-06-20 20:58 UTC, AliceProxy requested changes
Just a small typo, then LGTM

2022-06-20 20:58 UTC, AliceProxy commented on manifests/emissary/emissary-crds.yaml.in
> +            description: 'TODO(lukeshu): In v3alpha2, get rid of unnecessary nesting
Indeed

2022-06-20 20:58 UTC, AliceProxy commented on CHANGELOG.md
> +- Change: In the standard published `.yaml` files, now included is a `Moduel` resource that disables
`Module`?

2022-06-20 21:28 UTC, LukeShu commented on CHANGELOG.md
> +- Change: In the standard published `.yaml` files, now included is a `Moduel` resource that disables
Fixed.

2022-06-20 21:28 UTC, LukeShu commented
I've amended the final commit to fix the typo that Alice pointed out
```patch
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 052a5860e..644bc8ebc 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -92,7 +92,7 @@ it will be removed; but as it won't be user-visible this isn't considered a brea
   variable is now a misnomer, as it no longer configures which xDS API version is used, but it still
   affects what the default protocol used for a `TracingService` that points at Zipkin.
 
-- Change: In the standard published `.yaml` files, now included is a `Moduel` resource that disables
+- Change: In the standard published `.yaml` files, now included is a `Module` resource that disables
   the `/ambassador/v0/` → `127.0.0.1:8878` synthetic mapping.  We have long recommended to turn
   this off for production use; it is now off in the standard YAML.  The associated Helm chart
   release also now disables it by default.  A later apiVersion (`getambassador.io/v3alpha2` or
diff --git a/docs/releaseNotes.yml b/docs/releaseNotes.yml
index 0a454ada3..bae0d4b98 100644
--- a/docs/releaseNotes.yml
+++ b/docs/releaseNotes.yml
@@ -57,7 +57,7 @@ items:
       - title: Default YAML disables the diagnostics interface
         type: change
         body: >-
-          In the standard published <code>.yaml</code> files, now included is a <code>Moduel</code>
+          In the standard published <code>.yaml</code> files, now included is a <code>Module</code>
           resource that disables the <code>/ambassador/v0/</code> → <code>127.0.0.1:8878</code>
           synthetic mapping.  We have long recommended to turn this off for production use; it is
           now off in the standard YAML.  The associated Helm chart release also now disables it by
```

2022-06-21 00:04 UTC, AliceProxy approved these changes

2022-06-21 17:55 UTC, LanceEa approved these changes
lgtm

2022-06-21 18:18 UTC, merged