Synthetic v3 RateLimitService for Edge-Stack
emissary-ingress/emissary pull request #4324
Opened 2022-07-08 14:18 UTC by ddymko

Signed-off-by: David Dymko <ddymko@datawire.io>

## Description
With Edge-stack this will remove all `RateLimitService` that aren't using `procotol_version: v3` and inject a synthetic RateLimitService pointing at `127.0.0.1:8500` if there are no valid v3 RateLimitServices.

This is to ensure Edge-Stack always has a v3 RateLimitService available.

## Related Issues
List related issues.

## Testing
_pending_

## Checklist

 - [ ] I made sure to update `CHANGELOG.md`.

   Remember, the CHANGELOG needs to mention:
    + Any new features
    + Any changes to our included version of Envoy
    + Any non-backward-compatible changes
    + Any deprecations

 - [ ] This is unlikely to impact how Ambassador performs at scale.

   Remember, things that might have an impact at scale include:
    + Any significant changes in memory use that might require adjusting the memory limits
    + Any significant changes in CPU use that might require adjusting the CPU limits
    + Anything that might change how many replicas users should use
    + Changes that impact data-plane latency/scalability

 - [ ] My change is adequately tested.

   Remember when considering testing:
    + Your change needs to be specifically covered by tests.
       + Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
    + You also need to make sure that the _entire area being changed_ has adequate test coverage.
       + If existing tests don't actually cover the entire area being changed, add tests.
       + This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
    + We should lean on the bulk of code being covered by unit tests, but...
    + ... an end-to-end test should cover the integration points

 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

 - [ ] The changes in this PR have been reviewed for security concerns and adherence to security best practices.

2022-07-24 19:14 UTC, LanceEa commented
Note: a change log entry will be made when doing release later this week.

2022-07-24 19:15 UTC, LanceEa approved these changes
lgtm

2022-07-25 15:19 UTC, AliceProxy requested changes
lgtm but we should add a changelog for this since it is meant to reduce upgrade friction :+1:

2022-07-25 15:20 UTC, AliceProxy commented
> lgtm but we should add a changelog for this since it is meant to reduce upgrade friction +1

> Note: a change log entry will be made when doing release later this week.

Whoops nevermind then, lets get this landed.

2022-07-25 15:20 UTC, AliceProxy approved these changes

2022-07-25 15:20 UTC, LanceEa commented
@AliceProxy - here or on EdgeStack side?

2022-07-25 15:24 UTC, merged

2022-07-25 15:24 UTC, AliceProxy commented
> @AliceProxy - here or on EdgeStack side?

@LanceEa Here, but also for edge-stack. Ideally edge-stack.git's release notes should be kept up to date with emissary.git since changes to  Emissary impact Edge-Stack users.