Add RateLimitedAsResourceExhausted field to RateLimitServiceSpec
emissary-ingress/emissary pull request #5046
Opened 2023-05-13 22:33 UTC by jeromefroe

## Description

This commit adds a new field `RateLimitedAsResourceExhausted` to `RateLimitServiceSpec`
that can be used to configure the [corresponding `rate_limited_as_resource_exhausted` field](https://github.com/envoyproxy/envoy/blob/549164c42cae84b59154ca4c36009e408aa10b52/api/envoy/config/filter/http/rate_limit/v2/rate_limit.proto#L59)
in Envoy's `RateLimit` message.

I mostly based this PR off of #4464 which added the `FailureModeDeny` but please let me
know if I missed anything 😄 

## Related Issues

#3016

## Testing

I updated the tests in `test_irratelimit.py` to ensure the field is set in the rate limit config
when it is set in the spec.

## Checklist

- [ ] **Does my change need to be backported to a previous release?**
  - What backport versions were discussed with the Maintainers in the Issue?

- [x] **I made sure to update `CHANGELOG.md`.**

   Remember, the CHANGELOG needs to mention:
  - Any new features
  - Any changes to our included version of Envoy
  - Any non-backward-compatible changes
  - Any deprecations

- [x] **This is unlikely to impact how Ambassador performs at scale.**

   Remember, things that might have an impact at scale include:
  - Any significant changes in memory use that might require adjusting the memory limits
  - Any significant changes in CPU use that might require adjusting the CPU limits
  - Anything that might change how many replicas users should use
  - Changes that impact data-plane latency/scalability

- [ ] **My change is adequately tested.**

   Remember when considering testing:
  - Your change needs to be specifically covered by tests.
    - Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
  - You also need to make sure that the _entire area being changed_ has adequate test coverage.
    - If existing tests don't actually cover the entire area being changed, add tests.
    - This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
  - We should lean on the bulk of code being covered by unit tests, but...
  - ... an end-to-end test should cover the integration points

- [ ] **I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.**

- [ ] **The changes in this PR have been reviewed for security concerns and adherence to security best practices.**

2023-05-13 22:34 UTC, jeromefroe commented on CHANGELOG.md
> +- Feature: In Envoy 1.24, experimental support for a native OpenTelemetry tracing driver was
I'm not sure why these other formatting changes were made when I generate the Changelog, I'd be happy to remove though.

2023-06-06 21:05 UTC, cindymullins-dw commented
Hi @jeromefroe , FYI you're welcome to join our [Monthly Contributors meeting](https://github.com/emissary-ingress/emissary/blob/master/Community/MEETING_SCHEDULE.md#monthly-contributors-meeting) tomorrow, Wed June 7 at 3:30pm ET with our engineers.) to discuss this PR if that would be helpful to you.  Thanks for contributing!

2023-06-07 12:16 UTC, jeromefroe commented
Hi @cindymullins-dw! 👋 I won't be able to make the contributors meeting today unfortunately. Would it be possible to discuss the PR over comments? If not, I can aim to make the next one.

2023-07-04 17:05 UTC, cindymullins-dw commented
Hi @jeromefroe , just letting you know about tomorrow's [Monthly Contributors meeting](https://github.com/emissary-ingress/emissary/blob/master/Community/MEETING_SCHEDULE.md#monthly-contributors-meeting) tomorrow, Wed July 5 at 3:30pm ET with our engineers if you can make it.

2023-08-14 17:48 UTC, OmegaVVeapon commented
Hi, curious about this PR, has it been abandoned? I don't see any review comments on it.

This feature would be _greatly_ beneficial to Emissary users.

A RateLimit being hit is a client-side for which we'd like to **not** page out via our alerting platform. However, an `UNAVAILABLE` response could also mean that the upstream service is dead, something we'd very much like to page out for... currently, there's no way to know which is which.

2023-09-05 19:30 UTC, AliceProxy requested changes
I'm a plus 1 for supporting the feature. For the API, can we make it:

```yaml
spec:
  service: .....
  grpc:
    use_resource_exhausted_code: true/false
```

You will also need to add conversion support for the v2 CRDs by editing `pkg/api/getambassador.io/v2/crd_ratelimitservice.go`. Since all CRDs are stored in `v2`, whenever we add new fields to the `v3alpha1` CRDs, we have to go back and add them as a stubbed field in the `v2` CRDs just so the conversion can fully roundtrip and preserve the config. 

You can refer to the following snippet from `pkg/api/getambassador.io/v2/crd_authservice.go` for an example of how the conversion works.

```go
	// +k8s:conversion-gen:rename=CircuitBreakers
	V3CircuitBreakers []*CircuitBreaker `json:"v3CircuitBreakers,omitempty"`
```

Also you will need to sign your commits. You can sign new commits with: `git commit -m "my commit" --signoff` and rebase your old commits with a signoff like so: `git rebase HEAD~1 --signoff`

2023-09-14 22:46 UTC, AliceProxy commented
Hi @jeromefroe, I know it's been a while since you initially opened this PR. Would you still be available or interested in making the changes I asked for above so we can get your PR landed? If not, then no worries; I'll just cherry-pick your initial commit and apply those changes sometime in the next week or so when I find the time if you haven't addressed them in this PR by then. Cheers and thanks for the contribution.

2023-09-17 16:07 UTC, jeromefroe commented
Hey @AliceProxy! I'd be happy to make the changes and I should be to update this PR today. Thank you for the feedback!

2023-09-27 21:47 UTC, AliceProxy commented on CHANGELOG.md
> +- Feature: In Envoy 1.24, experimental support for a native OpenTelemetry tracing driver was
Don't worry too much about it, usually it's just editor settings or something like that.

2023-09-27 23:13 UTC, AliceProxy approved these changes
Hi @jeromefroe, thanks again for the contribution and sorry I got behind on reviewing this. Looks good to me other than a small issue with the lint check wanting to fix something, but I can take care of that. If you ever happen to open any other PRs, then feel free to ping me on our slack channel (https://a8r.io/slack) and I should be a lot faster to respond. Let me just get another maintainer to have a look and this should be available in the next release after it is merged.

2023-09-28 16:07 UTC, LanceEa approved these changes

2023-09-28 17:33 UTC, jeromefroe commented
Thank you @AliceProxy! Appreciate your feedback and review 🙇‍♂️

2023-09-28 20:36 UTC, merged